name: build-and-test
on: [push, pull_request]

jobs:
  windows-release:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    timeout-minutes: 500
    env:
      buildDir: '${{ github.workspace }}/build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          sdk: 10.0.19041.0
      - name: Restore deps from cache if they exist
        uses: actions/cache@v2
        with:
          path: |
            build/vcpkg_installed
          key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-build-release-${{ hashFiles('vcpkg.json') }}
      - name: Package into a zip
        run: .\scripts\windows\package.ps1
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nvui-fix
          if-no-files-found: ignore
          path: build/nvui
      - name: Rename nvui.zip to nvui-win64.zip for release upload
        if: startsWith(github.ref, 'refs/tags/')
        run: ren nvui.zip nvui-win64.zip
      - name: Upload Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: nvui-win64.zip
          tag: ${{ github.ref }}
          overwrite: false
          body: "Automated release by Github Actions."

